// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Proves the bridge is wired: Dart called Rust, Rust answered, the string
/// survived the crossing. The first thing to check on a new device, because it
/// fails differently from every later problem — a missing library rather than
/// a wrong answer.
Future<String> ping() => RustLib.instance.api.crateApiScannerPing();

/// Decode a photograph far enough to report its size.
///
/// Returns `Result`, where the M1 plan specified a panic with a note to tighten
/// it before M2. Deferring it was not safe to do: the bytes reaching this
/// function are a photograph the user just took or picked, and the failure
/// cases are ordinary rather than exotic — a truncated file, an interrupted
/// share, or an iOS HEIC, which this build cannot decode at all. A panic
/// unwinding across an FFI boundary is undefined behaviour in the general case
/// and a hard crash of the whole app in the friendly case. `flutter_rust_bridge`
/// maps `Err` onto a Dart exception, so the cost of doing it properly is one
/// `?` and a `match` in the UI.
Future<DecodedInfo> decodeDimensions({required List<int> bytes}) =>
    RustLib.instance.api.crateApiScannerDecodeDimensions(bytes: bytes);

/// What a photograph turned out to be, once the core had decoded it.
class DecodedInfo {
  final int width;
  final int height;

  const DecodedInfo({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedInfo &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
